[tool.black]
line-length = 88
target-version = ["py310"]
extend-exclude = '''
/(
    | env
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 310
skip_glob = ["env/*"]
src_paths = ["app"]


[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]